branches:
  only:
    - master
environment:
  tag_name: "%APPVEYOR_REPO_TAG_NAME%"
  release_name: "ezipay-magento-1.x_v%appveyor_repo_tag_name%.zip"
before_build:
  - ps: (Get-Content app/code/community/Ezipay/Ezipayments/etc/config.xml).replace("ezipay_plugin_version_placeholder", $env:APPVEYOR_REPO_TAG_NAME ) | Set-Content app/code/community/Ezipay/Ezipayments/etc/config.xml
build_script:
  - ps: Invoke-Expression "7z a $env:release_name -xr'!.git' -x'!appveyor.yml' -x'!.gitignore' -xr'!.vscode' -xr'!test'"
artifacts:
  - path: $(release_name)
    name: $(tag_name)
    type: zip
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: v$(APPVEYOR_REPO_TAG_NAME)
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
    auth_token:
      secure: vsGwkhjaQdCumvOvqTywfnwRMULrvO50y6GwVNF2FHe04dYKbEXyfhO6OMdUsaED
    artifact: /.*\.zip/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Email
    to:
      - devadmin@oxipay.com.au
  - provider: Slack
    auth_token:
      secure: yXpzER0fyDmh7wYR6zrrES+wGzz5010OpUvpb5UPMsQZO12Ag3TaeOjSsZ0tDQQ4WaNoNngsPOPiaYWmsfg3fhJrSyPy240FqSwDdhSPqC0=
    channel: '#alerts'
